// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxEIh3l3qlAEcd-gJO8kpyKoUk6fl7q1M',
    appId: '1:671926549475:web:a255240f62693780007ed6',
    messagingSenderId: '671926549475',
    projectId: 'ridezo-fbe63',
    authDomain: 'ridezo-fbe63.firebaseapp.com',
    storageBucket: 'ridezo-fbe63.firebasestorage.app',
    measurementId: 'G-8KSXJHYMM8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7UEkwQLgUf79chVfuPBroe3FEbyQAsQ8',
    appId: '1:671926549475:android:bc46a2f929e3ccae007ed6',
    messagingSenderId: '671926549475',
    projectId: 'ridezo-fbe63',
    storageBucket: 'ridezo-fbe63.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXXaghkmDUI2kiwoc-HRuThjDiiOgEXdc',
    appId: '1:671926549475:ios:648e34d2a65ae12b007ed6',
    messagingSenderId: '671926549475',
    projectId: 'ridezo-fbe63',
    storageBucket: 'ridezo-fbe63.firebasestorage.app',
    iosBundleId: 'com.shoumik.hunterheads',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXXaghkmDUI2kiwoc-HRuThjDiiOgEXdc',
    appId: '1:671926549475:ios:1abd7c83dd9d165c007ed6',
    messagingSenderId: '671926549475',
    projectId: 'ridezo-fbe63',
    storageBucket: 'ridezo-fbe63.firebasestorage.app',
    iosBundleId: 'com.example.rideZo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBxEIh3l3qlAEcd-gJO8kpyKoUk6fl7q1M',
    appId: '1:671926549475:web:a6bdec1a6dea3a45007ed6',
    messagingSenderId: '671926549475',
    projectId: 'ridezo-fbe63',
    authDomain: 'ridezo-fbe63.firebaseapp.com',
    storageBucket: 'ridezo-fbe63.firebasestorage.app',
    measurementId: 'G-XJ45EJ4G77',
  );
}
